export const upcomingTrips = [
  {
    id: 1,
    title: "Delhi to Dharamshala / McLeodganj Premium Tour",
    cost: "₹8,500",
    duration: "4N/5D",
    location: "Dharamshala",
    rating: 4.9,
    reviews: 120,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_1946_c7fb31d5ee.png&w=640&q=50",
  },
  {
    id: 2,
    title: "Kheerganga Trek + Kasol + Tosh",
    cost: "₹8,000",
    duration: "4N/5D",
    location: "Parvati Valley",
    rating: 4.8,
    reviews: 156,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_8758_c9c3f79a7d.png&w=640&q=50",
  },
  {
    id: 3,
    title: "Manali Private Tour for Couples",
    cost: "₹6,999",
    duration: "4N/5D",
    location: "Manali",
    rating: 4.9,
    reviews: 230,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2Fharrison_fitts_VX_Hq_JN_52_K6s_unsplash_4a2e08f528.jpg&w=640&q=50",
  },
  {
    id: 4,
    title: "Chopta + Tungnath + Deoriatal Package",
    cost: "₹6,500",
    duration: "4N/5D",
    location: "Chopta",
    rating: 4.9,
    reviews: 85,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_1946_c7fb31d5ee.png&w=640&q=50",
  }
];

export const recommendedTrips = [
  {
    id: 1,
    title: "Masai Mara Trip: The Great Migration Dream",
    price: "₹1,69,999",
    originalPrice: "₹1,89,999",
    duration: "7-days package",
    type: "FIT | Group",
    rating: "4.9",
    reviews: "100",
    date: "5 Sept",
    saveTag: "Save ₹20,000",
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_1946_c7fb31d5ee.png&w=640&q=50",
  },
  {
    id: 2,
    title: "Valley of Flowers Trip, Hemkund Sahib, Badrinath",
    price: "₹10,999",
    originalPrice: null,
    duration: "6-days package",
    type: "Group",
    rating: "4.9",
    reviews: "100",
    date: "10 Jul",
    saveTag: null,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_8758_c9c3f79a7d.png&w=640&q=50",
  },
  {
    id: 3,
    title: "Spain Backpacking - La Tomatina Special",
    price: "₹1,34,999",
    originalPrice: "₹1,49,999",
    duration: "9-days package",
    type: "FIT | Group",
    rating: "4.9",
    reviews: "100",
    date: "23 Aug",
    saveTag: "Save ₹15,000",
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2Fharrison_fitts_VX_Hq_JN_52_K6s_unsplash_4a2e08f528.jpg&w=640&q=50",
  },
  {
    id: 4,
    title: "Ultimate Iceland Expedition",
    price: "₹2,59,999",
    originalPrice: "₹2,79,999",
    duration: "10-days package",
    type: "FIT | Group",
    rating: "New",
    reviews: null,
    date: "20 Sept",
    saveTag: "Save ₹20,000",
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_1946_c7fb31d5ee.png&w=640&q=50",
  }
];

export const domesticGetaways = [
  {
    id: 1,
    title: "Delhi to Dharamshala / McLeodganj Premium Tour",
    price: "₹8,500",
    originalPrice: "₹9,500",
    duration: "4N/5D",
    type: "Group",
    rating: "4.9",
    reviews: "120",
    date: "Multiple Dates",
    saveTag: null,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_8758_c9c3f79a7d.png&w=640&q=50",
  },
  {
    id: 2,
    title: "Kheerganga Trek + Kasol + Tosh",
    price: "₹8,000",
    originalPrice: null,
    duration: "4N/5D",
    type: "Group",
    rating: "4.8",
    reviews: "156",
    date: "Every Weekend",
    saveTag: "Bestseller",
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2Fharrison_fitts_VX_Hq_JN_52_K6s_unsplash_4a2e08f528.jpg&w=640&q=50",
  },
  {
    id: 3,
    title: "Manali Private Tour for Couples",
    price: "₹6,999",
    originalPrice: "₹8,500",
    duration: "4N/5D",
    type: "Private",
    rating: "4.9",
    reviews: "230",
    date: "Custom Dates",
    saveTag: "Save ₹1,501",
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_1946_c7fb31d5ee.png&w=640&q=50",
  },
  {
    id: 4,
    title: "Chopta + Tungnath + Deoriatal Package",
    price: "₹6,500",
    originalPrice: null,
    duration: "4N/5D",
    type: "Group",
    rating: "4.9",
    reviews: "85",
    date: "Multiple Dates",
    saveTag: null,
    imageUrl: "https://www.deshvideshtravels.com/_next/image?url=https%3A%2F%2Fdeshvideshstrapi.s3.ap-south-1.amazonaws.com%2FIMG_8758_c9c3f79a7d.png&w=640&q=50",
  }
];
